# Generated by Django 4.2.9 on 2026-04-05 11:45

import apps.restaurants.models.cash_desk
import apps.restaurants.models.restaurant
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0001_initial'),
        ('floor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('legal_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name_uz_crl', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('address_uz_crl', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('auth_code', models.CharField(default=apps.restaurants.models.restaurant.generate_restaurant_auth_code, max_length=6, unique=True)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_order_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='platform.businesspartner')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PrepStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('kind', models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar'), ('other', 'Other')], default='kitchen', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_stations', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DistributionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('kind', models.CharField(choices=[('hall', 'Hall'), ('online', 'Online'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='hall', max_length=20)),
                ('integration_channel', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_points', to='floor.hall')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_points', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('kitchen_display', 'Kitchen Display'), ('owner_dashboard', 'Owner Dashboard')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_halls', models.ManyToManyField(blank=True, related_name='allowed_devices', to='floor.hall')),
                ('primary_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_devices', to='floor.hall')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CashDesk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('enabled_payment_methods', models.JSONField(blank=True, default=apps.restaurants.models.cash_desk.default_enabled_payment_methods)),
                ('fiscal_provider', models.CharField(choices=[('mock', 'Mock')], default='mock', max_length=32)),
                ('receipt_printer_enabled', models.BooleanField(default=True)),
                ('terminal_id', models.CharField(blank=True, max_length=120)),
                ('external_cashbox_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_desks', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
