# Generated by Django 4.2.9 on 2026-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='faktura_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
