# Generated by Django 4.2.9 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_delete_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='fiscal_provider',
            field=models.CharField(
                choices=[('mock', 'Mock'), ('soliq-ofd', 'Soliq OFD')],
                default='mock',
                max_length=32,
            ),
        ),
    ]
