# Generated by Django 4.2.30 on 2026-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_restaurant_parent_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_total_mode',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('cashier_editable', 'Cashier editable')], default='fixed', max_length=32),
        ),
    ]
