# Generated by Django 5.2.17 on 2026-09-21 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_restaurant_single_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_policies', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
    ]
