# Generated by Django 4.2.30 on 2026-08-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('local_agents', '0004_localagent_lan_endpoints_protocol_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='localagent',
            name='credential_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localagent',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_agent_record', to='devices.device'),
        ),
    ]
