# Generated by Django 5.2.17 on 2026-09-04 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_agents', '0008_localagentconnection'),
        ('restaurants', '0028_restore_auth_code_rollback_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='localagentcommand',
            name='financial_operation_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='localagentcommand',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='LocalAgentMutationInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_id', models.CharField(max_length=128, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('operation', models.JSONField()),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('owner_epoch', models.CharField(blank=True, max_length=128)),
                ('sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('depends_on', models.JSONField(default=list)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('needs_review', 'Needs review'), ('conflict', 'Conflict')], default='received', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(default=dict)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAgentMutationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('operation', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='local_agents.localagentmutationinbox')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='localagentmutationinbox',
            index=models.Index(fields=['restaurant', 'state'], name='agent_inbox_rest_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='localagentmutationinbox',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__isnull', False), models.Q(('owner_epoch', ''), _negated=True)), fields=('restaurant', 'owner_epoch', 'sequence'), name='agent_inbox_owner_sequence_uniq'),
        ),
    ]
