# Generated by Django 4.2.9 on 2026-03-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_branch_status_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('branch', 'order_number'), name='orders_unique_branch_order_number'),
        ),
    ]
