# Generated by Django 4.2.9 on 2026-03-30 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_branch_legal_name_branch_tax_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_orders_unique_branch_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='last_reprinted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reprint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'QR'), ('mixed', 'Mixed')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash_amount', models.PositiveIntegerField(default=0)),
                ('actual_closing_cash_amount', models.PositiveIntegerField(default=0)),
                ('expected_closing_cash_amount', models.PositiveIntegerField(default=0)),
                ('cash_difference_amount', models.IntegerField(default=0)),
                ('cash_total', models.PositiveIntegerField(default=0)),
                ('card_total', models.PositiveIntegerField(default=0)),
                ('qr_total', models.PositiveIntegerField(default=0)),
                ('refund_total', models.PositiveIntegerField(default=0)),
                ('receipt_count', models.PositiveIntegerField(default=0)),
                ('reprint_count', models.PositiveIntegerField(default=0)),
                ('notes_open', models.TextField(blank=True)),
                ('notes_close', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='organizations.branch')),
                ('cash_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='organizations.cashdesk')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_shifts', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.cashshift'),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.payment')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'refunded_at'], name='paymentrefund_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['branch', 'status'], name='cashshift_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['branch', 'opened_at'], name='cashshift_branch_opened_idx'),
        ),
    ]
