# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_receipt_last_reprinted_at_receipt_reprint_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_unique_branch_order_number',
        ),
        migrations.RemoveIndex(
            model_name='cashshift',
            name='cashshift_branch_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashshift',
            name='cashshift_branch_opened_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_branch_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_branch_closed_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_branch_created_idx',
        ),
        migrations.RemoveField(
            model_name='cashshift',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['cash_desk', 'status'], name='cashshift_cashdesk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['cash_desk', 'opened_at'], name='cashshift_cashdesk_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='order_restaurant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'closed_at'], name='order_restaurant_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'created_at'], name='order_restaurant_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('restaurant', 'order_number'), name='orders_unique_restaurant_order_number'),
        ),
    ]
