# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('channel', models.CharField(choices=[('hall', 'Hall'), ('takeaway', 'Takeaway'), ('online', 'Online'), ('delivery', 'Delivery')], default='hall', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('ready', 'Ready'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('line_total', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('cooking', 'Cooking'), ('done', 'Done'), ('served', 'Served'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItemNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sales.orderitem')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
