# Generated by Django 4.2.9 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
