# Generated by Django 4.2.30 on 2026-07-24 11:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_base_unit_price(apps, schema_editor):
    OrderItem = apps.get_model('sales', 'OrderItem')
    OrderItem.objects.filter(base_unit_price=0).update(base_unit_price=models.F('unit_price'))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_modifiergroup_modifieroption_and_more'),
        ('sales', '0008_order_delivery_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='base_unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_base_unit_price, migrations.RunPython.noop),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=255)),
                ('option_name', models.CharField(max_length=255)),
                ('price_delta', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('modifier_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_snapshots', to='catalog.modifieroption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='sales.orderitem')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
    ]
