# Generated by Django 4.2.30 on 2026-08-12 15:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_existing_totals(apps, schema_editor):
    Order = apps.get_model('sales', 'Order')
    Order.objects.all().update(calculated_total=models.F('total'))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0009_orderitem_base_unit_price_orderitemmodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calculated_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(copy_existing_totals, migrations.RunPython.noop),
        migrations.AddField(
            model_name='order',
            name='total_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_overridden_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='total_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_override_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram')], default='piece', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12),
        ),
    ]
