# Generated by Django 4.2.30 on 2026-08-14 14:15

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def backfill_restaurant_service_fee_snapshot(apps, schema_editor):
    Order = apps.get_model("sales", "Order")
    for order in Order.objects.select_related("restaurant").iterator():
        subtotal = int(order.subtotal or 0)
        charged_fee = max(int(order.calculated_total or 0) - subtotal, 0)
        if subtotal > 0:
            percent = (
                Decimal(charged_fee) * Decimal("100") / Decimal(subtotal)
            ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        elif getattr(order.restaurant, "service_fee_enabled", False):
            percent = Decimal(str(order.restaurant.service_fee_percent or 0))
        else:
            percent = Decimal("0")
        Order.objects.filter(pk=order.pk).update(restaurant_service_fee_percent=percent)


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0010_order_calculated_total_order_total_overridden_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="hall_service_fee_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant_service_fee_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="table_service_fee_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.RunPython(
            backfill_restaurant_service_fee_snapshot,
            migrations.RunPython.noop,
        ),
    ]
