# Generated by Django 5.2.17 on 2026-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_hourly_service_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sale_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('pors', 'Portion')], default='piece', max_length=16),
        ),
    ]
