# Generated by Django 4.2.9 on 2026-03-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='description_uz_crl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='name_uz_crl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_uz_crl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_uz_crl',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
