# Generated by Django 4.2.9 on 2026-03-30 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_employee_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    EmployeeProfile = apps.get_model('accounts', 'EmployeeProfile')
    EmployeeCompensationProfile = apps.get_model('accounts', 'EmployeeCompensationProfile')

    for user in User.objects.all().iterator():
        EmployeeProfile.objects.get_or_create(user=user)
        EmployeeCompensationProfile.objects.get_or_create(user=user)


def delete_employee_profiles(apps, schema_editor):
    EmployeeProfile = apps.get_model('accounts', 'EmployeeProfile')
    EmployeeCompensationProfile = apps.get_model('accounts', 'EmployeeCompensationProfile')
    EmployeeCompensationProfile.objects.all().delete()
    EmployeeProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_series', models.CharField(blank=True, default='', max_length=32)),
                ('pnfl', models.CharField(blank=True, default='', max_length=32)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_type', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('kpi', 'KPI')], default='', max_length=16)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kpi_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_compensation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
        migrations.RunPython(create_employee_profiles, delete_employee_profiles),
    ]
