# Generated by Django 4.2.9 on 2026-04-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_employee_compensation_salary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actor_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ui_mode',
        ),
    ]
