# Generated by Django 4.2.9 on 2026-04-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_actor_type_remove_user_ui_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authsession',
            name='ui_channel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allowed_halls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_partner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hall_switch_permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_hall',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='BusinessPartnerUserProfile',
        ),
    ]
