# Generated by Django 4.2.9 on 2026-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeeprofile_employeecompensationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actor_type',
            field=models.CharField(choices=[('product_owner', 'Product owner'), ('business_partner', 'Business partner'), ('restaurant_admin', 'Restaurant admin'), ('restaurant_staff', 'Restaurant staff')], default='restaurant_staff', max_length=30),
        ),
    ]
