# Generated by Django 4.2.9 on 2026-03-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_actor_type'),
        ('organizations', '0010_featureconfig_entitlement_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.businesspartner'),
        ),
    ]
