# Generated by Django 4.2.9 on 2026-04-04 23:25

from django.db import migrations, models


def copy_employee_compensation_into_employee_profile(apps, schema_editor):
    EmployeeProfile = apps.get_model('accounts', 'EmployeeProfile')
    EmployeeCompensationProfile = apps.get_model('accounts', 'EmployeeCompensationProfile')

    for compensation in EmployeeCompensationProfile.objects.all().iterator():
        profile, _ = EmployeeProfile.objects.get_or_create(user_id=compensation.user_id)
        profile.salary_type = compensation.salary_type
        profile.base_amount = compensation.base_amount
        profile.kpi_percent = compensation.kpi_percent
        profile.save(update_fields=['salary_type', 'base_amount', 'kpi_percent'])


def copy_employee_profile_back_to_compensation(apps, schema_editor):
    EmployeeProfile = apps.get_model('accounts', 'EmployeeProfile')
    EmployeeCompensationProfile = apps.get_model('accounts', 'EmployeeCompensationProfile')

    for profile in EmployeeProfile.objects.exclude(
        salary_type='',
        base_amount=None,
        kpi_percent=None,
    ).iterator():
        EmployeeCompensationProfile.objects.update_or_create(
            user_id=profile.user_id,
            defaults={
                'salary_type': profile.salary_type,
                'base_amount': profile.base_amount,
                'kpi_percent': profile.kpi_percent,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_refactor_user_profiles_and_auth_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='kpi_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='salary_type',
            field=models.CharField(
                blank=True,
                choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')],
                default='',
                max_length=16,
            ),
        ),
        migrations.RunPython(
            copy_employee_compensation_into_employee_profile,
            copy_employee_profile_back_to_compensation,
        ),
        migrations.DeleteModel(
            name='EmployeeCompensationProfile',
        ),
        migrations.RenameModel(
            old_name='RestaurantUserProfile',
            new_name='RestaurantProfile',
        ),
    ]
