# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_businesspartneruserprofile_restaurantuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
    ]
