# Generated by Django 4.2.9 on 2026-03-31 09:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=16)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='accounts.permission')),
            ],
            options={
                'ordering': ('url', 'method'),
            },
        ),
        migrations.AddConstraint(
            model_name='permissionendpoint',
            constraint=models.UniqueConstraint(fields=('url', 'method'), name='accounts_permission_endpoint_route_method_uniq'),
        ),
    ]
