# Generated by Django 4.2.9 on 2026-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_permissionendpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='permission',
            name='group_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='permission',
            name='resource',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='permission',
            name='surface',
            field=models.CharField(choices=[('admin', 'Admin'), ('pos', 'POS'), ('dashboard', 'Dashboard'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='permission',
            name='ui_visible',
            field=models.BooleanField(default=True),
        ),
    ]
