[tool.poetry]
name = "cafe-postcode-backend"
version = "0.1.0"
description = "Backend service for the cafe-postcode.uz restaurant POS platform."
authors = ["Nazarbek"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django-class-settings = "*"
daphne = "*"
django = "4.2.9"
django-cors-headers = "*"
django-extensions = "*"
django-filter = "*"
django-modeltranslation = "*"
django-nested-inline = "*"
django-q = "1.3.6"
djangorestframework = "*"
djangorestframework-camel-case = "*"
emoji = "*"
django-debug-toolbar = "^4.2.0"
django-solo = "^2.1.0"
psycopg2-binary = "^2.9.9"
pillow = "*"
django-storages = "^1.14.6"
boto3 = "^1.39.11"
pytelegrambotapi = "^4.14.0"
psutil = "^5.9.5"
drf-extra-fields = "^3.7.0"
whitenoise = "^6.5.0"
redis = "^5.0.1"
django-hint = "^0.3.2"
openpyxl = "^3.1.2"
gunicorn = "^21.2.0"
drf-yasg = "*"
channels = "^4.0.0"
python-levenshtein = "^0.24.0"
numpy = "^1.26.4"
httpx = "^0.28.1"
djangorestframework-stubs = "^3.16.8"
cryptography = "^45.0.5"
django-prometheus = "^2.4.1"
python-json-logger = "^4.1.0"
channels-redis = "^4.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
loadtest = [
    "locust (>=2.43.4,<3.0.0)"
]
