# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash_amount', models.PositiveIntegerField(default=0)),
                ('actual_closing_cash_amount', models.PositiveIntegerField(default=0)),
                ('expected_closing_cash_amount', models.PositiveIntegerField(default=0)),
                ('cash_difference_amount', models.IntegerField(default=0)),
                ('cash_total', models.PositiveIntegerField(default=0)),
                ('card_total', models.PositiveIntegerField(default=0)),
                ('qr_total', models.PositiveIntegerField(default=0)),
                ('refund_total', models.PositiveIntegerField(default=0)),
                ('receipt_count', models.PositiveIntegerField(default=0)),
                ('reprint_count', models.PositiveIntegerField(default=0)),
                ('notes_open', models.TextField(blank=True)),
                ('notes_close', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'QR'), ('mixed', 'Mixed')], default='cash', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=120)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('prebill', 'Prebill'), ('fiscal', 'Fiscal'), ('refund', 'Refund')], default='fiscal', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('failed', 'Failed')], default='created', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reprint_count', models.PositiveIntegerField(default=0)),
                ('last_reprinted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
