# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_initial'),
        ('sales', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrefund',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='restaurants.cashdesk'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.cashshift'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='cash_desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='restaurants.cashdesk'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['status', 'refunded_at'], name='paymentrefund_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payment_status_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['cash_desk', 'status'], name='cashshift_cashdesk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashshift',
            index=models.Index(fields=['cash_desk', 'opened_at'], name='cashshift_cashdesk_opened_idx'),
        ),
    ]
