# Generated by Django 4.2.9 on 2026-05-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0012_merge_unikassa_and_pos_auth_background'),
        ('billing', '0007_cashshift_cashier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalShiftSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('terminal_id', models.CharField(blank=True, max_length=120)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('open_payload', models.JSONField(blank=True, default=dict)),
                ('close_payload', models.JSONField(blank=True, default=dict)),
                ('cash_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_shift_sessions', to='restaurants.cashdesk')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_shift_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_fiscal_shift_sessions', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_shift_sessions', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('-opened_at',),
                'indexes': [models.Index(fields=['restaurant', 'status'], name='fiscalshift_rest_status_idx'), models.Index(fields=['restaurant', 'opened_at'], name='fiscalshift_rest_opened_idx'), models.Index(fields=['cash_desk', 'status'], name='fiscalshift_desk_status_idx')],
            },
        ),
    ]
