# Generated by Django 5.2.17 on 2026-09-04 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_expense_category_cash_expense'),
        ('printing', '0013_publish_service_fee_rate_labels'),
        ('sales', '0012_hourly_service_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceiptAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='cashshift',
            name='edge_close_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='reconciliation_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscalshiftsession',
            name='edge_session_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='financial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='origin_cash_shift_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fiscal_session_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='receipt',
            name='registration_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='split_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reconciling', 'Historical shift awaiting close evidence')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Registration outcome unknown')], default='created', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('split_key', ''), _negated=True), fields=('payment', 'kind', 'split_key'), name='receipt_payment_split_unique'),
        ),
        migrations.AddField(
            model_name='fiscalreceiptattempt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_attempts', to='billing.receipt'),
        ),
        migrations.AddConstraint(
            model_name='fiscalreceiptattempt',
            constraint=models.UniqueConstraint(fields=('receipt', 'payload_hash'), name='fiscal_attempt_evidence_unique'),
        ),
    ]
