# Generated by Django 5.2.17 on 2026-09-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_fiscalreceiptattempt_cashshift_edge_close_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrefund',
            name='cash_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_refunds', to='billing.cashshift'),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='edge_operation_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
