# Generated by Django 5.2.17 on 2026-09-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_paymentrefund_cash_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalshiftsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reconciling', 'Reconciling historical evidence')], default='open', max_length=20),
        ),
    ]
