# Generated by Django 4.2.9 on 2026-03-23 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('fiscal', 'Fiscal'), ('payment', 'Payment'), ('printer', 'Printer')], max_length=20)),
                ('provider', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('mock', 'Mock'), ('live', 'Live')], default='mock', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='organizations.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('kind', 'provider'),
                'unique_together': {('restaurant', 'branch', 'kind', 'provider')},
            },
        ),
    ]
