# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('fiscal', 'Fiscal'), ('payment', 'Payment'), ('printer', 'Printer')], max_length=20)),
                ('provider', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('mock', 'Mock'), ('live', 'Live')], default='mock', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('kind', 'provider'),
            },
        ),
    ]
