# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_restaurant_auth_code'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('restaurant', 'kind', 'provider')},
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='branch',
        ),
    ]
