# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='restaurants.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('restaurant', 'kind', 'provider')},
        ),
    ]
