from django.urls import path

from apps.admin.views import (
    BranchDetailView,
    BranchListCreateView,
    CashDeskDetailView,
    CashDeskListCreateView,
    DeviceDetailView,
    DeviceListCreateView,
    DiningTableDetailView,
    DiningTableListCreateView,
    DistributionPointDetailView,
    DistributionPointListCreateView,
    HallConstructorView,
    HallDetailView,
    HallListCreateView,
    PrepStationDetailView,
    PrepStationListCreateView,
    RestaurantDetailView,
    RestaurantFeatureConfigView,
    RestaurantListCreateView,
    RestaurantConfigView,
    TableSessionDetailView,
    TableSessionListCreateView,
)

urlpatterns = [
    path('constructor/restaurant/', RestaurantConfigView.as_view()),
    path('constructor/branches/', BranchListCreateView.as_view()),
    path('constructor/branches/<uuid:pk>/', BranchDetailView.as_view()),
    path('restaurants/<uuid:restaurant_id>/feature-config/', RestaurantFeatureConfigView.as_view()),
    path('floor/halls/', HallListCreateView.as_view()),
    path('floor/halls/<uuid:pk>/', HallDetailView.as_view()),
    path('floor/halls/<uuid:pk>/constructor/', HallConstructorView.as_view()),
    path('floor/tables/', DiningTableListCreateView.as_view()),
    path('floor/tables/<uuid:pk>/', DiningTableDetailView.as_view()),
    path('floor/table-sessions/', TableSessionListCreateView.as_view()),
    path('floor/table-sessions/<uuid:pk>/', TableSessionDetailView.as_view()),
    path('constructor/prep-stations/', PrepStationListCreateView.as_view()),
    path('constructor/prep-stations/<uuid:pk>/', PrepStationDetailView.as_view()),
    path('constructor/cash-desks/', CashDeskListCreateView.as_view()),
    path('constructor/cash-desks/<uuid:pk>/', CashDeskDetailView.as_view()),
    path('constructor/devices/', DeviceListCreateView.as_view()),
    path('constructor/devices/<uuid:pk>/', DeviceDetailView.as_view()),
    path('constructor/distribution-points/', DistributionPointListCreateView.as_view()),
    path('constructor/distribution-points/<uuid:pk>/', DistributionPointDetailView.as_view()),
    path('constructor/restaurants/', RestaurantListCreateView.as_view()),
    path('constructor/restaurants/<uuid:pk>/', RestaurantDetailView.as_view()),
]
