# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('cooking', 'Cooking'), ('done', 'Done')], default='new', max_length=20)),
                ('routed_via', models.CharField(choices=[('display', 'Display'), ('printer', 'Printer'), ('both', 'Both')], default='display', max_length=20)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_payload', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
