# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0001_initial'),
        ('sales', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='sales.order'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='prep_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='restaurants.prepstation'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='restaurants.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchenticket',
            unique_together={('order', 'prep_station')},
        ),
    ]
