# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenticket',
            name='branch',
        ),
    ]
