# Generated by Django 4.2.30 on 2026-07-16 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_remove_unikassa_provider'),
        ('kitchen', '0004_kitchenticket_print_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvMonitorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('restaurant_auth_code_hash', models.CharField(max_length=64)),
                ('paired_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_monitor_devices', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TvMonitorPairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll_token_hash', models.CharField(max_length=64, unique=True)),
                ('claim_token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing', to='kitchen.tvmonitordevice')),
            ],
            options={
                'indexes': [models.Index(fields=['claimed_at', 'expires_at'], name='tv_pair_claimed_exp_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tvmonitordevice',
            index=models.Index(fields=['restaurant', 'revoked_at'], name='tv_device_rest_revoked_idx'),
        ),
    ]
