# Generated by Django 4.2.30 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_tvmonitordevice_tvmonitorpairing_and_more'),
        ('sales', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=64)),
                ('locale', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=8)),
                ('kind', models.CharField(choices=[('auto', 'Automatic'), ('replay', 'Replay')], default='auto', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kitchen_announcements', to='users.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_announcements', to='sales.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_announcements', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='ka_rest_created_idx')],
                'constraints': [models.UniqueConstraint(condition=Q(('kind', 'auto')), fields=('order',), name='unique_auto_kitchen_announcement')],
            },
        ),
    ]
