# Generated by Django 5.2.16 on 2026-08-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0003_device_legacy_migration_key'),
        ('kitchen', '0007_kitchen_ticket_dispatch_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvmonitordevice',
            name='credential_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvmonitordevice',
            name='device',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='legacy_tv_monitor_record',
                to='devices.device',
            ),
        ),
    ]
