# Generated by Django 4.2.30 on 2026-08-16 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0024_alter_restaurant_vat_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('POS_TERMINAL', 'POS terminal'), ('LOCAL_AGENT', 'Local Agent'), ('TV_MONITOR', 'TV monitor'), ('CONTROL_DEVICE', 'Control device')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('public_key_algorithm', models.CharField(choices=[('ED25519', 'Ed25519'), ('P256_SHA256', 'ECDSA P-256 SHA-256')], max_length=32)),
                ('public_key', models.TextField()),
                ('public_key_fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paired_at', models.DateTimeField()),
                ('lease_expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=500)),
                ('paired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_devices', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='restaurants.restaurant')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('restaurant__name', 'type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('auth_session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_security_events', to=settings.AUTH_USER_MODEL)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='devices.device')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='security_rest_created_idx'), models.Index(fields=['severity', '-created_at'], name='security_sev_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='DevicePairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('POS_TERMINAL', 'POS terminal'), ('LOCAL_AGENT', 'Local Agent'), ('TV_MONITOR', 'TV monitor'), ('CONTROL_DEVICE', 'Control device')], max_length=32)),
                ('requested_name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('public_key_algorithm', models.CharField(choices=[('ED25519', 'Ed25519'), ('P256_SHA256', 'ECDSA P-256 SHA-256')], max_length=32)),
                ('public_key', models.TextField()),
                ('public_key_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('poll_token_hash', models.CharField(max_length=64, unique=True)),
                ('claim_token_hash', models.CharField(max_length=64, unique=True)),
                ('display_code', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_device_pairings', to=settings.AUTH_USER_MODEL)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing', to='devices.device')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_device_pairings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='device_pair_status_exp_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['restaurant', 'type', 'status'], name='device_rest_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'last_seen_at'], name='device_status_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(check=models.Q(('type', 'CONTROL_DEVICE'), ('restaurant__isnull', False), _connector='OR'), name='device_restaurant_required'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE'), ('type', 'LOCAL_AGENT')), fields=('restaurant',), name='one_active_agent_device_per_restaurant'),
        ),
    ]
