# Generated by Django 4.2.30 on 2026-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepairing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='devicepairing',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('public_key_fingerprint',), name='one_pending_pairing_per_device_key'),
        ),
    ]
