# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='users.role'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='users.permission'),
        ),
        migrations.AddField(
            model_name='restaurantentitlement',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='restaurant_entitlements', to='users.role'),
        ),
        migrations.AddField(
            model_name='restaurantentitlement',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='restaurant_entitlements', to='users.permission'),
        ),
        migrations.AddField(
            model_name='restaurantentitlement',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantentitlement',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_entitlements', to='platform.tariff'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='owner_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_partner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
