# Generated by Django 4.2.9 on 2026-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantentitlement',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='restaurantentitlement',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
