# Generated by Django 4.2.9 on 2026-07-10 10:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


PRINT_KINDS = ('kitchen_ticket', 'payment_receipt_plain', 'payment_receipt_fiscal')


def _initial_layout(kind):
    blocks = [
        {
            'id': 'restaurant-name',
            'type': 'text',
            'role': 'restaurant_header',
            'text': '{{restaurant.name}}',
            'align': 'center',
            'bold': True,
        },
        {
            'id': 'order-meta',
            'type': 'metadata',
            'role': 'order_header',
            'rows': [{'label': 'Buyurtma', 'value': '{{order.displayNumber}}'}],
        },
        {
            'id': 'items',
            'type': 'items_table',
            'role': 'items',
            'columns': [
                {'label': 'Nomi', 'value': '{{item.name}}'},
                {'label': 'Soni', 'value': '{{item.quantity}}'},
            ],
        },
    ]
    if kind != 'kitchen_ticket':
        blocks.extend(
            [
                {
                    'id': 'totals',
                    'type': 'totals',
                    'role': 'totals',
                    'rows': [{'label': 'JAMI', 'value': '{{totals.total}}', 'format': 'money'}],
                },
                {
                    'id': 'payment',
                    'type': 'metadata',
                    'role': 'payment',
                    'rows': [{'label': "To'lov", 'value': '{{payment.method}}'}],
                },
            ]
        )
    if kind == 'payment_receipt_fiscal':
        blocks.extend(
            [
                {
                    'id': 'fiscal',
                    'type': 'metadata',
                    'role': 'fiscal',
                    'locked': True,
                    'rows': [{'label': 'Fiskal chek', 'value': '{{fiscal.receiptNumber}}'}],
                },
                {
                    'id': 'fiscal-qr',
                    'type': 'qr',
                    'role': 'fiscal_qr',
                    'locked': True,
                    'value': '{{fiscal.qrUrl}}',
                },
            ]
        )
    blocks.extend([{'id': 'feed', 'type': 'feed', 'lines': 4}, {'id': 'cut', 'type': 'cut'}])
    return {'schemaVersion': 1, 'paperWidthMm': 80, 'blocks': blocks}


def create_existing_restaurant_templates(apps, schema_editor):
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    PrintTemplate = apps.get_model('printing', 'PrintTemplate')
    PrintTemplateVersion = apps.get_model('printing', 'PrintTemplateVersion')
    now = timezone.now()
    for restaurant_id in Restaurant.objects.values_list('id', flat=True).iterator():
        for kind in PRINT_KINDS:
            template, _ = PrintTemplate.objects.get_or_create(restaurant_id=restaurant_id, kind=kind)
            if template.published_version_id:
                continue
            version = PrintTemplateVersion.objects.create(
                template=template,
                revision=1,
                schema_version=1,
                status='published',
                preset_key='standard_80',
                layout=_initial_layout(kind),
                published_at=now,
            )
            template.published_version_id = version.id
            template.save(update_fields=('published_version', 'updated_at'))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('integrations', '0010_allow_multiple_integration_configs_per_provider'),
        ('restaurants', '0019_restaurant_marking_check_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('kitchen_ticket', 'Kitchen ticket'), ('payment_receipt_plain', 'Plain payment receipt'), ('payment_receipt_fiscal', 'Fiscal payment receipt')], max_length=40)),
                ('operation_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('test', 'Test')], default='sale', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_documents', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_documents', to='restaurants.restaurant')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('kitchen_ticket', 'Kitchen ticket'), ('payment_receipt_plain', 'Plain payment receipt'), ('payment_receipt_fiscal', 'Fiscal payment receipt')], max_length=40)),
            ],
            options={'ordering': ('kind',)},
        ),
        migrations.CreateModel(
            name='PrintTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('preset_key', models.CharField(blank=True, max_length=40)),
                ('layout', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='printing.printtemplate')),
            ],
            options={'ordering': ('-revision',)},
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_by_templates', to='printing.printtemplateversion'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('dispatched', 'Dispatched'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dispatch_unknown', 'Dispatch unknown')], default='queued', max_length=24)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='restaurants.cashdesk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='printing.printdocument')),
                ('prep_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='restaurants.prepstation')),
                ('printer_integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='integrations.integrationconfig')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='restaurants.restaurant')),
            ],
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='printdocument',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='printing.printtemplateversion'),
        ),
        migrations.AddConstraint(model_name='printtemplateversion', constraint=models.UniqueConstraint(fields=('template', 'revision'), name='prt_tpl_rev_uniq')),
        migrations.AddConstraint(model_name='printtemplate', constraint=models.UniqueConstraint(fields=('restaurant', 'kind'), name='prt_tpl_rest_kind_uniq')),
        migrations.AddIndex(model_name='printjob', index=models.Index(fields=['restaurant', 'status', 'created_at'], name='prt_job_rest_status_created')),
        migrations.AddConstraint(model_name='printjob', constraint=models.UniqueConstraint(fields=('restaurant', 'idempotency_key'), name='prt_job_idem_uniq')),
        migrations.AddConstraint(model_name='printjob', constraint=models.CheckConstraint(check=models.Q(('copies__gte', 1)), name='prt_job_copies_gte_1')),
        migrations.AddIndex(model_name='printdocument', index=models.Index(fields=['restaurant', 'kind', 'created_at'], name='prt_doc_rest_kind_created')),
        migrations.AddIndex(model_name='printdocument', index=models.Index(fields=['source_model', 'source_id'], name='prt_doc_source_idx')),
        migrations.AddConstraint(model_name='printdocument', constraint=models.UniqueConstraint(fields=('restaurant', 'idempotency_key'), name='prt_doc_idem_uniq')),
        migrations.RunPython(create_existing_restaurant_templates, migrations.RunPython.noop),
    ]
