# Generated by Django 5.2.17 on 2026-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementbotupdate',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
