# Generated by Django 4.2.30 on 2026-08-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_alter_restaurant_vat_enabled'),
        ('devices', '0001_initial'),
        ('users', '0002_authsession_surface_and_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='authsession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authsession',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='restaurants.restaurant'),
        ),
    ]
