# Generated by Django 5.2.17 on 2026-09-06 00:42

import apps.inventory.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_catalogitem_archived_at'),
        ('restaurants', '0028_restore_auth_code_rollback_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.inventory.models.attachment_storage, upload_to=apps.inventory.models.attachment_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('base_unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('piece', 'dona')], max_length=10)),
                ('purchase_unit', models.CharField(blank=True, max_length=30)),
                ('purchase_factor', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('min_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tolerance_percent', models.DecimalField(decimal_places=3, default=5, max_digits=8)),
                ('tolerance_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tolerance_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('availability_mode', models.CharField(choices=[('off', 'Off'), ('warn', 'Warn'), ('block', 'Block')], default='warn', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('version', models.PositiveIntegerField()),
                ('yield_quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('trigger', models.CharField(choices=[('dispatch', 'Dispatch'), ('sale', 'Sale')], default='dispatch', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogitem')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('catalog_item__name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('modifier_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.modifieroption')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.recipe')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('opening', 'Boshlang‘ich qoldiq'), ('receipt', 'Kirim'), ('issue', 'Chiqim'), ('supplier_return', 'Yetkazib beruvchiga qaytarish'), ('customer_return', 'Mijozdan qaytish'), ('stocktake', 'Inventarizatsiya'), ('sale', 'Retsept sarfi'), ('sale_return', 'Sarfni qaytarish'), ('reversal', 'Bekor qiluvchi hujjat')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment_url', models.URLField(blank=True, max_length=1000)),
                ('responsible_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('request_digest', models.CharField(blank=True, max_length=64)),
                ('created_by_name', models.CharField(blank=True, max_length=200)),
                ('posted_by_name', models.CharField(blank=True, max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stockdocument')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.UUIDField()),
                ('order_item_id', models.UUIDField(unique=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('resolved_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('components', models.JSONField(default=list)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
                ('source_consumption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.orderconsumption')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.recipe')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumptionResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=200)),
                ('disposition', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='inventory.orderconsumption')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockdocument')),
            ],
        ),
        migrations.CreateModel(
            name='StockDocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('base_unit', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('count_recorded', models.BooleanField(default=True)),
                ('input_unit', models.CharField(default='base', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('expected_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('expected_revision', models.PositiveBigIntegerField(default=0)),
                ('variance_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('variance_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('consumption_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('tolerance_percent', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('tolerance_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('tolerance_value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stockdocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=20)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('valuation_adjustment', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=20)),
                ('revision', models.PositiveBigIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('order_item', models.UUIDField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockdocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='inventory.stockdocumentline')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='orderconsumption',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='inv_item_name'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('restaurant', 'sku'), name='inv_item_sku'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_factor__gt', 0)), name='inv_item_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 0), ('tolerance_percent__gte', 0), ('tolerance_quantity__gte', 0), ('tolerance_value__gte', 0)), name='inv_item_threshold_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('catalog_item', 'version'), name='inv_recipe_version'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('catalog_item',), name='inv_recipe_active'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('yield_quantity__gt', 0)), name='inv_recipe_positive_yield'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_recipe_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='consumptionresolution',
            constraint=models.UniqueConstraint(fields=('consumption', 'event_key'), name='inv_resolution_event'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='inv_supplier_name'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='inv_warehouse_name'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('restaurant',), name='inv_default_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'item', '-created_at'], name='inv_movement_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.UniqueConstraint(fields=('restaurant', 'number'), name='inv_document_number'),
        ),
        migrations.AddConstraint(
            model_name='stockdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('restaurant', 'idempotency_key'), name='inv_document_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item'), name='inv_balance_warehouse_item'),
        ),
    ]
