# Generated by Django 5.2.17 on 2026-09-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionresolution',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
