# Generated by Django 5.2.17 on 2026-09-16 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_catalogitem_barcode'),
        ('inventory', '0002_consumptionresolution_created_by_name'),
        ('restaurants', '0029_restaurant_single_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('catalog_item__name', 'output_item__name', '-version')},
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='inv_recipe_version',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='inv_recipe_active',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='kind',
            field=models.CharField(choices=[('raw', 'Xomashyo'), ('semi_finished', 'Yarim tayyor mahsulot'), ('finished', 'Tayyor mahsulot'), ('packaging', 'Qadoqlash'), ('non_food', 'Xo‘jalik mahsuloti')], default='raw', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_recipes', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_documents', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='planned_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='production_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_documents', to='inventory.recipe'),
        ),
        migrations.AddField(
            model_name='stockdocumentline',
            name='role',
            field=models.CharField(choices=[('normal', 'Oddiy'), ('input', 'Xomashyo'), ('output', 'Natija')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='kind',
            field=models.CharField(choices=[('general', 'Umumiy'), ('raw', 'Xomashyo'), ('production', 'Ishlab chiqarish'), ('sales', 'Sotuv')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogitem'),
        ),
        migrations.AlterField(
            model_name='stockdocument',
            name='kind',
            field=models.CharField(choices=[('opening', 'Boshlang‘ich qoldiq'), ('receipt', 'Kirim'), ('issue', 'Chiqim'), ('supplier_return', 'Yetkazib beruvchiga qaytarish'), ('customer_return', 'Mijozdan qaytish'), ('stocktake', 'Inventarizatsiya'), ('sale', 'Retsept sarfi'), ('sale_return', 'Sarfni qaytarish'), ('transfer', 'Omborlararo transfer'), ('production', 'Ishlab chiqarish'), ('reversal', 'Bekor qiluvchi hujjat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockdocumentline'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_item__isnull', False)), fields=('catalog_item', 'version'), name='inv_recipe_version'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_item__isnull', False), ('is_active', True)), fields=('catalog_item',), name='inv_recipe_active'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('output_item__isnull', False)), fields=('output_item', 'version'), name='inv_prep_recipe_version'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('output_item__isnull', False)), fields=('output_item',), name='inv_prep_recipe_active'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_item__isnull', False), ('output_item__isnull', True)), models.Q(('catalog_item__isnull', True), ('output_item__isnull', False)), _connector='OR'), name='inv_recipe_one_output'),
        ),
    ]
