# Generated by Django 5.2.17 on 2026-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocumentline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stockdocumentline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stockdocumentline',
            name='list_unit_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
