# Generated by Django 5.2.17 on 2026-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockdocumentline_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeline',
            name='modifier_condition',
            field=models.CharField(choices=[('selected', 'When selected'), ('not_selected', 'When not selected')], default='selected', max_length=16),
        ),
    ]
