# Generated by Django 4.2.9 on 2026-04-02 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('table_number', models.PositiveIntegerField()),
                ('seat_count', models.PositiveIntegerField(default=4)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('round', 'Round'), ('oval', 'Oval')], default='square', max_length=20)),
                ('shape_variant', models.CharField(choices=[('seat2_horizontal', '2 Seat Horizontal'), ('seat2_vertical', '2 Seat Vertical'), ('seat3_triangle', '3 Seat Triangle'), ('seat4_square', '4 Seat Square'), ('seat4_horizontal', '4 Seat Horizontal'), ('seat4_vertical', '4 Seat Vertical'), ('seat5_horizontal', '5 Seat Horizontal'), ('seat5_vertical', '5 Seat Vertical'), ('seat6_horizontal', '6 Seat Horizontal'), ('seat6_vertical', '6 Seat Vertical')], default='seat4_square', max_length=32)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('position_x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('table_number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('description_uz_crl', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('grid_columns', models.PositiveIntegerField(default=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_payment', 'Pending Payment'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ZoneOrCabin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
