# Generated by Django 4.2.9 on 2026-03-23 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(blank=True)),
                ('table_number', models.PositiveIntegerField()),
                ('seat_count', models.PositiveIntegerField(default=4)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('round', 'Round'), ('oval', 'Oval')], default='square', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('position_x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=120, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=120, max_digits=8)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('table_number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LayoutObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('table', 'Table'), ('bar', 'Bar'), ('cash_desk', 'Cash Desk'), ('door', 'Door'), ('wall', 'Wall'), ('decor', 'Decor'), ('label', 'Label')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('position_x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=120, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=120, max_digits=8)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ZoneOrCabin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='floor.hall')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_payment', 'Pending Payment'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_table_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
