# Generated by Django 4.2.9 on 2026-03-23 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='floor.hall'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_children', to='floor.tablesession'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_table_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='organizations.restaurant'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='floor.diningtable'),
        ),
        migrations.AddField(
            model_name='layouttemplate',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_templates', to='organizations.restaurant'),
        ),
        migrations.AddField(
            model_name='layoutobject',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_objects', to='floor.hall'),
        ),
        migrations.AddField(
            model_name='layoutobject',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_objects', to='floor.diningtable'),
        ),
        migrations.AddField(
            model_name='layoutobject',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_objects', to='floor.zoneorcabin'),
        ),
        migrations.AddField(
            model_name='hall',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='hall',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='organizations.restaurant'),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='floor.hall'),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='floor.zoneorcabin'),
        ),
        migrations.AlterUniqueTogether(
            name='zoneorcabin',
            unique_together={('hall', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='layouttemplate',
            unique_together={('restaurant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('branch', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='diningtable',
            unique_together={('hall', 'table_number')},
        ),
    ]
