# Generated by Django 4.2.9 on 2026-04-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floor', '0002_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_table_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='floor.hall'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_children', to='floor.tablesession'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_table_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='floor.diningtable'),
        ),
        migrations.AddField(
            model_name='hall',
            name='zone_or_cabin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='halls', to='floor.zoneorcabin'),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='floor.hall'),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='floor.zoneorcabin'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['restaurant', 'status'], name='tblsess_rest_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diningtable',
            unique_together={('hall', 'table_number')},
        ),
    ]
