# Generated by Django 4.2.9 on 2026-03-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uz_crl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_uz_crl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zoneorcabin',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zoneorcabin',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zoneorcabin',
            name='name_uz_crl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
