# Generated by Django 4.2.9 on 2026-03-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0003_hall_description_ru_hall_description_uz_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['branch', 'status'], name='tablesess_branch_status_idx'),
        ),
    ]
