# Generated by Django 4.2.30 on 2026-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningtable',
            name='service_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningtable',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hall',
            name='service_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hall',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
