# Generated by Django 4.2.9 on 2026-03-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0004_tablesession_tablesess_branch_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningtable',
            name='shape_variant',
            field=models.CharField(choices=[('seat2_horizontal', '2 Seat Horizontal'), ('seat2_vertical', '2 Seat Vertical'), ('seat3_triangle', '3 Seat Triangle'), ('seat4_square', '4 Seat Square'), ('seat4_horizontal', '4 Seat Horizontal'), ('seat4_vertical', '4 Seat Vertical'), ('seat5_horizontal', '5 Seat Horizontal'), ('seat5_vertical', '5 Seat Vertical'), ('seat6_horizontal', '6 Seat Horizontal'), ('seat6_vertical', '6 Seat Vertical')], default='seat4_square', max_length=32),
        ),
        migrations.AddField(
            model_name='hall',
            name='grid_columns',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
