# Generated by Django 4.2.9 on 2026-03-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0006_hall_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='layouttemplate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='zoneorcabin',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='diningtable',
            name='code',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='code',
        ),
        migrations.RemoveField(
            model_name='layouttemplate',
            name='code',
        ),
        migrations.RemoveField(
            model_name='zoneorcabin',
            name='code',
        ),
    ]
