# Generated by Django 4.2.9 on 2026-03-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0007_alter_hall_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='level',
        ),
    ]
