# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0008_remove_hall_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tablesession',
            name='tablesess_branch_status_idx',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tablesession',
            name='branch',
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['restaurant', 'status'], name='tblsess_rest_status_idx'),
        ),
    ]
