# Generated by Django 5.2.17 on 2026-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0008_diningtable_string_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningtable',
            name='service_fee_formula',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hall',
            name='service_fee_formula',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='service_fee_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('hourly', 'Hourly'), ('formula', 'Formula')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='hall',
            name='service_fee_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('hourly', 'Hourly'), ('formula', 'Formula')], default='percentage', max_length=20),
        ),
    ]
