# Generated by Django 5.2.17 on 2026-09-08 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_fiscalshiftsession_status'),
        ('telegram_reports', '0002_telegramlinktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramShiftDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_chunk', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_reports.telegramaccount')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cashshift')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'shift'), name='telegram_unique_shift_delivery')],
            },
        ),
    ]
