API_PREFIX = 'api/'
API_VERSION = 'v1'
API_V1_PREFIX = f'{API_PREFIX}{API_VERSION}/'
PAGE_SIZE_QUERY_PARAM = 'page_size'

MINI_PAGE_SIZE = 3
DEFAULT_PAGE_SIZE = 10
STANDARD_PAGE_SIZE = 20
LARGE_PAGE_SIZE = 50
MAX_PAGE_SIZE = 50
