"""Generate client contracts from common/sale_units.json; --check detects drift.

Run from any directory: python backend/scripts/generate_sale_units.py [--check]
Sibling repositories must be available in the Cafe Postcode workspace.
"""
import argparse
import json
import subprocess
from pathlib import Path

backend = Path(__file__).resolve().parents[1]
source = backend / 'common/sale_units.json'
rules = json.loads(source.read_text(encoding='utf-8'))
helper = """
export type SaleUnit = keyof typeof SALE_UNITS;
export const SALE_UNIT_IDS = Object.keys(SALE_UNITS) as [SaleUnit, ...SaleUnit[]];
export const DEFAULT_SALE_UNIT: SaleUnit = 'piece';
export function getSaleUnit(unit?: string | null) {
  if (unit === undefined || unit === null || unit === '') return SALE_UNITS[DEFAULT_SALE_UNIT];
  if (!Object.prototype.hasOwnProperty.call(SALE_UNITS, unit)) throw new Error(`Unknown sale unit: ${unit}`);
  return SALE_UNITS[unit as SaleUnit];
}
export function saleUnitLabel(unit?: string | null, locale = 'uz') {
  const labels = getSaleUnit(unit).labels;
  return labels[locale as keyof typeof labels] ?? labels.uz;
}
export function isValidSaleQuantity(value: number, unit?: string | null, allowZero = false) {
  const rule = getSaleUnit(unit);
  const scaled = value * 1000;
  return Number.isFinite(value) && value >= (allowZero ? 0 : rule.step) && value <= 999_999_999.999
    && Math.abs(scaled - Math.round(scaled)) < 0.0000001
    && Math.round(scaled) % Math.round(rule.step * 1000) === 0;
}
"""
ts = '// Generated by backend/scripts/generate_sale_units.py. Do not edit.\n'
ts += 'export const SALE_UNITS = ' + json.dumps(rules, ensure_ascii=False, indent=2) + ' as const;\n' + helper
outputs = {backend.parent / project / 'src/shared/domain/sale-units.ts': ts
           for project in ['admin-frontend', 'pos-frontend', 'dashboard-frontend']}
outputs[backend.parent / 'local-agent/cmd/local-agent/sale_units.json'] = source.read_text(encoding='utf-8')
check = argparse.ArgumentParser()
check.add_argument('--check', action='store_true')
args = check.parse_args()
failed = []
for path, content in outputs.items():
    if path.suffix == '.ts':
        project = path.parents[3]
        prettier = project / 'node_modules/prettier/bin/prettier.cjs'
        if not prettier.exists():
            prettier = project / 'node_modules/prettier/bin/prettier.mjs'
        content = subprocess.run(['node', str(prettier), '--stdin-filepath', str(path)],
                                 input=content, capture_output=True, text=True, encoding='utf-8', cwd=project, check=True).stdout
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            failed.append(str(path))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8', newline='\n')
if failed:
    raise SystemExit('Sale-unit contract drift: ' + ', '.join(failed))
print('Sale-unit contracts verified.' if args.check else 'Sale-unit contracts generated.')
