# Generated by Django 4.2.9 on 2026-03-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.catalogcategory'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='prep_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='organizations.prepstation'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='organizations.restaurant'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='organizations.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitemprice',
            unique_together={('item', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together={('branch', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogcategory',
            unique_together={('branch', 'code')},
        ),
    ]
