# Generated by Django 4.2.9 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='mxik_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='mxik_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
