# Generated by Django 4.2.9 on 2026-03-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='name_uz_crl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='description_uz_crl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name_uz_crl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitemprice',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeline',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
