# Generated by Django 4.2.9 on 2026-03-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogcategory_name_ru_catalogcategory_name_uz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeLine',
        ),
    ]
