# Generated by Django 4.2.9 on 2026-04-18 08:10

import apps.catalog.models.catalog_category
import apps.catalog.models.catalog_item
import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_mxik_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=common.storages.CatalogCategoryImageStorage, upload_to=apps.catalog.models.catalog_category.catalog_category_image_upload_to),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=common.storages.CatalogItemImageStorage, upload_to=apps.catalog.models.catalog_item.catalog_item_image_upload_to),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image_source',
            field=models.CharField(blank=True, choices=[('mxik-cache', 'MXIK cache'), ('manual', 'Manual')], max_length=32),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
