# Generated by Django 4.2.9 on 2026-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_recipeline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='mxik_code',
            field=models.CharField(blank=True, db_index=True, max_length=17),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='mxik_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='mxik_code',
            field=models.CharField(blank=True, db_index=True, max_length=17),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='mxik_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CatalogItemPrice',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='code',
        ),
    ]
