# Generated by Django 4.2.9 on 2026-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalogcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='image_source',
            field=models.CharField(
                blank=True,
                choices=[('mxik-cache', 'MXIK cache'), ('manual', 'Manual')],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
