# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogcategory_image_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogcategory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='sku',
        ),
    ]
