# Generated by Django 4.2.30 on 2026-07-24 11:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_remove_unikassa_provider'),
        ('catalog', '0008_catalogcategory_prep_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('selection_type', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice')], default='single', max_length=16)),
                ('min_selections', models.PositiveSmallIntegerField(default=0)),
                ('max_selections', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('price_delta', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CatalogItemModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_assignments', to='catalog.catalogitem')),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_assignments', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ('sort_order', 'modifier_group__sort_order', 'modifier_group__name'),
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='modifier_groups',
            field=models.ManyToManyField(blank=True, related_name='catalog_items', through='catalog.CatalogItemModifierGroup', to='catalog.modifiergroup'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='modifier_option_unique_group_name'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('group', 'name_uz'), name='modifier_option_unique_group_name-name_uz'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('group', 'name_uz_crl'), name='modifier_option_unique_group_name-name_uz_crl'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('group', 'name_ru'), name='modifier_option_unique_group_name-name_ru'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='modifier_group_unique_restaurant_name'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name_uz'), name='modifier_group_unique_restaurant_name-name_uz'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name_uz_crl'), name='modifier_group_unique_restaurant_name-name_uz_crl'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name_ru'), name='modifier_group_unique_restaurant_name-name_ru'),
        ),
        migrations.AddConstraint(
            model_name='catalogitemmodifiergroup',
            constraint=models.UniqueConstraint(fields=('catalog_item', 'modifier_group'), name='catalog_item_modifier_group_unique_assignment'),
        ),
    ]
