# Generated by Django 4.2.30 on 2026-08-08 06:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_restaurant_parent_restaurant'),
        ('catalog', '0010_catalogitem_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItemGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='catalog.catalogcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_groups', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CatalogItemGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_name', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('catalog_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='catalog.catalogitem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='catalog.catalogitemgroup')),
            ],
            options={
                'ordering': ('sort_order', 'catalog_item__sort_order', 'catalog_item__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='catalogitemgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'sort_order'), name='catalog_item_group_unique_member_order'),
        ),
        migrations.AddConstraint(
            model_name='catalogitemgroup',
            constraint=models.UniqueConstraint(fields=('restaurant', 'category', 'name'), name='catalog_item_group_unique_name_per_category'),
        ),
    ]
