# Generated by Django 4.2.30 on 2026-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_catalogitemgroup_catalogitemgroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='sale_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram')], default='piece', max_length=16),
        ),
    ]
