# Generated by Django 4.2.9 on 2026-04-02 12:01

import apps.organizations.models.cash_desk
import apps.organizations.models.restaurant
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('floor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inn', models.CharField(max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('director_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('faktura_payload', models.JSONField(blank=True, default=dict)),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('legal_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name_uz_crl', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('address_uz_crl', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('auth_code', models.CharField(default=apps.organizations.models.restaurant.generate_restaurant_auth_code, max_length=6, unique=True)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_order_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='organizations.businesspartner')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], default='basic', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('operational_settings', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='tariffs', to='accounts.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='tariffs', to='accounts.permission')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('operational_settings', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='restaurant_entitlements', to='accounts.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='restaurant_entitlements', to='accounts.permission')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to='organizations.restaurant')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_entitlements', to='organizations.tariff')),
            ],
            options={
                'ordering': ('restaurant__name',),
            },
        ),
        migrations.CreateModel(
            name='PrepStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('kind', models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar'), ('other', 'Other')], default='kitchen', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_stations', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall_enabled', models.BooleanField(default=True)),
                ('kitchen_enabled', models.BooleanField(default=True)),
                ('cashier_enabled', models.BooleanField(default=True)),
                ('owner_dashboard_enabled', models.BooleanField(default=True)),
                ('order_entry_mode', models.CharField(choices=[('hall', 'Hall'), ('cashier_builder', 'Cashier builder')], default='hall', max_length=32)),
                ('kitchen_mode', models.CharField(choices=[('display', 'Display'), ('printer', 'Printer'), ('both', 'Both')], default='display', max_length=20)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('enabled_roles', models.JSONField(blank=True, default=list)),
                ('entitlement_overrides', models.JSONField(blank=True, default=dict)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='organizations.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_uz_crl', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('kind', models.CharField(choices=[('hall', 'Hall'), ('online', 'Online'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='hall', max_length=20)),
                ('integration_channel', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_points', to='floor.hall')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_points', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('kitchen_display', 'Kitchen Display'), ('owner_dashboard', 'Owner Dashboard')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_halls', models.ManyToManyField(blank=True, related_name='allowed_devices', to='floor.hall')),
                ('primary_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_devices', to='floor.hall')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CashDesk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('enabled_payment_methods', models.JSONField(blank=True, default=apps.organizations.models.cash_desk.default_enabled_payment_methods)),
                ('fiscal_provider', models.CharField(choices=[('mock', 'Mock')], default='mock', max_length=32)),
                ('receipt_printer_enabled', models.BooleanField(default=True)),
                ('terminal_id', models.CharField(blank=True, max_length=120)),
                ('external_cashbox_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_desks', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
