# Generated by Django 4.2.9 on 2026-03-23 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_number', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall_enabled', models.BooleanField(default=True)),
                ('kitchen_enabled', models.BooleanField(default=True)),
                ('cashier_enabled', models.BooleanField(default=True)),
                ('owner_dashboard_enabled', models.BooleanField(default=True)),
                ('kitchen_mode', models.CharField(choices=[('display', 'Display'), ('printer', 'Printer'), ('both', 'Both')], default='display', max_length=20)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('enabled_roles', models.JSONField(blank=True, default=list)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='organizations.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistributionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('hall', 'Hall'), ('online', 'Online'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='hall', max_length=20)),
                ('integration_channel', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_points', to='floor.hall')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_points', to='organizations.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_points', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CashDesk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_desks', to='organizations.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_desks', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.restaurant'),
        ),
        migrations.CreateModel(
            name='PrepStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar'), ('other', 'Other')], default='kitchen', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_stations', to='organizations.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_stations', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField()),
                ('mode', models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('kitchen_display', 'Kitchen Display'), ('owner_dashboard', 'Owner Dashboard')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='floor.hall')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.restaurant')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('restaurant', 'code')},
        ),
    ]
