# Generated by Django 4.2.9 on 2026-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_distributionpoint_name_ru_distributionpoint_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='order_entry_mode',
            field=models.CharField(choices=[('hall', 'Hall'), ('cashier_builder', 'Cashier builder')], default='hall', max_length=32),
        ),
    ]
