# Generated by Django 4.2.9 on 2026-03-28 13:35

from django.db import migrations, models
from django.db.models import Max


def seed_last_order_number(apps, schema_editor):
    Branch = apps.get_model('organizations', 'Branch')
    Order = apps.get_model('orders', 'Order')

    for branch in Branch.objects.all().iterator():
        max_order_number = Order.objects.filter(branch_id=branch.pk).aggregate(max_order_number=Max('order_number')).get(
            'max_order_number'
        ) or 0
        if branch.last_order_number != max_order_number:
            branch.last_order_number = max_order_number
            branch.save(update_fields=['last_order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_restaurant_timezone'),
        ('orders', '0004_order_orders_unique_branch_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_order_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_last_order_number, migrations.RunPython.noop),
    ]
