# Generated by Django 4.2.9 on 2026-03-30 11:57

from django.db import migrations, models
import django.db.models.deletion


def backfill_allowed_halls(apps, schema_editor):
    Device = apps.get_model('organizations', 'Device')

    for device in Device.objects.exclude(primary_hall__isnull=True).iterator():
        device.allowed_halls.add(device.primary_hall_id)


def clear_allowed_halls(apps, schema_editor):
    Device = apps.get_model('organizations', 'Device')
    through_model = Device.allowed_halls.through
    through_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0006_hall_level'),
        ('organizations', '0006_branch_last_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='assigned_hall',
            new_name='primary_hall',
        ),
        migrations.AddField(
            model_name='device',
            name='allowed_halls',
            field=models.ManyToManyField(blank=True, related_name='allowed_devices', to='floor.hall'),
        ),
        migrations.RunPython(backfill_allowed_halls, clear_allowed_halls),
    ]
