# Generated by Django 4.2.9 on 2026-03-30 12:14

import apps.organizations.models.cash_desk
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor', '0006_hall_level'),
        ('organizations', '0007_remove_device_assigned_hall_device_allowed_halls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='tax_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='vat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='enabled_payment_methods',
            field=models.JSONField(blank=True, default=apps.organizations.models.cash_desk.default_enabled_payment_methods),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='external_cashbox_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='fiscal_provider',
            field=models.CharField(choices=[('mock', 'Mock')], default='mock', max_length=32),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='receipt_printer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashdesk',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='device',
            name='primary_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_devices', to='floor.hall'),
        ),
    ]
