# Generated by Django 4.2.9 on 2026-03-30 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_actor_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0009_backfill_branch_fiscal_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='entitlement_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_order_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], default='basic', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('operational_settings', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='tariffs', to='accounts.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='tariffs', to='accounts.permission')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('operational_settings', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='restaurant_entitlements', to='accounts.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='restaurant_entitlements', to='accounts.permission')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to='organizations.restaurant')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_entitlements', to='organizations.tariff')),
            ],
            options={
                'ordering': ('restaurant__name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inn', models.CharField(max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('director_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('faktura_payload', models.JSONField(blank=True, default=dict)),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='business_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='organizations.businesspartner'),
        ),
    ]
