# Generated by Django 4.2.9 on 2026-03-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_featureconfig_entitlement_overrides_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prepstation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
        migrations.RemoveField(
            model_name='device',
            name='code',
        ),
        migrations.RemoveField(
            model_name='prepstation',
            name='code',
        ),
    ]
