# Generated by Django 4.2.9 on 2026-03-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_branch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_desks', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='distributionpoint',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_points', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='prepstation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_stations', to='organizations.branch'),
        ),
    ]
