# Generated by Django 4.2.9 on 2026-03-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_orders_unique_branch_order_number_and_more'),
        ('kitchen', '0002_remove_kitchenticket_branch'),
        ('accounts', '0009_remove_user_branch'),
        ('integrations', '0002_alter_integrationconfig_unique_together_and_more'),
        ('catalog', '0007_remove_catalogcategory_branch_and_more'),
        ('floor', '0009_remove_tablesession_tablesess_branch_status_idx_and_more'),
        ('organizations', '0013_restaurant_auth_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdesk',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='device',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='distributionpoint',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='prepstation',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
